{
  "name": "agora_mobile",
  "description": "agora mobile client",
  "version": "0.1.0",
  "homepage": "https://agora.io",
  "environment": {
    "sdk": ">=3.0.0 <4.0.0"
  },
  "dependencies": {
    "flutter": {
      "sdk": "flutter"
    },
    "cupertino_icons": "^1.0.2"
  },
  "dev_dependencies": {
    "flutter_test": {
      "sdk": "flutter"
    },
    "flutter_lints": "^3.0.0"
  },
  "flutter": {
    "uses-material-design": true
  }
}
